version: "3.8"
services:
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: tts_piper
    volumes:
      - ./backend/modelos:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PIPER_VOICE=pt_BR-silvia-low

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - piper